### ISSUE TITLE
Clarification Request for non-terminal fragments

### ISSUE THREAD

**Issue by gorryfair** [tsvwg/draft-ietf-tsvwg-udp-options#1]
On Thu, Jun 29, 2023 at 9:28 AM Erik Auerswald wrote:
> I do not understand how both "[n]on-terminal fragments never have
> options after the fragment" and "The RDOS field enables the FRAG option
> to precede other options in every fragment" can be true at the same time.

**Comment by gorryfair** [comment]
Seems related to:
https://mailarchive.ietf.org/arch/msg/tsvwg/D99trU_nsq4rRGT24gNeeDnkfoE/

**Comment by Mike-Heard** [comment]
Specific text to fix the issues with Section 9.4 was suggested in:

https://mailarchive.ietf.org/arch/msg/tsvwg/0RptobbqczCVoOy-B8L_CJaj25w/

**Comment by jtouch** [comment]
Text incorporated in -23 already. Please advise if this resolves this issue.

**Comment by gorryfair** [comment]
Discussed at Interim and closed.
