### ISSUE TITLE
* Section 22: should compare TCP and UDP

### ISSUE THREAD

**Issue by gorryfair** [tsvwg/draft-ietf-tsvwg-udp-options#11]
Erik: > * Section 22: The second paragraph seems intended to compare UDP options
>   with TCP options, but it uses only "UDP", resulting in the tautology
>   that the UDP security implications are not substantially different
>   from security implications of UDP options:
>
>   OLD:
>
>    Note that any user application that considers UDP options to affect
>    security need not enable them. However, their use does not impact
>    security in a way substantially different than UDP options;
>
>   NEW:
>
>    Note that any user application that considers UDP options to affect
>    security need not enable them. However, their use does not impact
>    security in a way substantially different than TCP options;

This issue was first  raised in
https://mailarchive.ietf.org/arch/msg/tsvwg/ocDWz4jWZdqVP6CTuAhsBXer2Bc/
and also at earlier stages.

- Appears to still need consdieration

**Comment by jtouch** [comment]
Fixed in -23.

**Comment by gorryfair** [comment]
Discussed at Interim and closed.
