### ISSUE TITLE
* Section 9.6: Change "segment" to "datagram"

### ISSUE THREAD

**Issue by Mike-Heard** [tsvwg/draft-ietf-tsvwg-udp-options#13]
Raised by Mike Heard and Erik Auerswald.

**Comment by gorryfair** [comment]
Unsure of what is requested to change here, but I am already confused by:
the "FRAG option of the first segment", which I thought was the first part of the datagram"?

**Comment by Mike-Heard** [comment]
This is the change that was requested:

OLD:
largest reassembled UDP segment

NEW:
largest reassembled UDP datagram

**Comment by gorryfair** [comment]
The text in draft-ietf-tsvwg-udp-options-22 reads:
     Note: per packet options can occur either at the end of the
      original user data or be placed after the FRAG option of the
      first segment, with the Reassembled Datagram Option Start (RDOS)

**Comment by Mike-Heard** [comment]
The text you quote is in Section 9.4, not in section 9.6, so the comment
should be about issue #3, not about issue #13.

**Comment by gorryfair** [comment]
Ah moving that part to issue #13.

**Comment by jtouch** [comment]
Segment has been changed to datagram everywhere it refers to UDP. Additional text in the terminology section to explain that the original intent - of 1:1 correspondence with IP datagrams - is changed herein.

**Comment by gorryfair** [comment]
Discussed at Interim and closed.
