### ISSUE TITLE
* Section 22: Specify that RES may be sent other than on return traffic only when DLPMTUD is enabled.

### ISSUE THREAD

**Issue by Mike-Heard** [tsvwg/draft-ietf-tsvwg-udp-options#15]
Raised by Erik Auerswald. See https://mailarchive.ietf.org/arch/msg/tsvwg/qlcFuZjzlzxyoFg2UOhv-PK8Kag/

**Comment by auerswal** [comment]
Suggested text for an adjusted REQ/RES description in https://mailarchive.ietf.org/arch/msg/tsvwg/mdPPObp-ULgSWWQnJbh3SEeYdTE/

**Comment by gorryfair** [comment]
I'm OK with the proposed text, as long as we explain the application isn't always the "application", but it is always a protocol above UDP Options.

**Comment by jtouch** [comment]
I updated the text in -23 to try to explain this. Note the security caution in that section.

**Comment by gorryfair** [comment]
The new words look good, but we ought to have gone further when we note  DPLPMTUD ….   initiate UDP responses in the absence of user transmission

- I think we ought to go further and add words that clarify that the RES  response is only when the receiver has enabled for DPLPMTUD for the socket pair.

**Comment by jtouch** [comment]
REQ/RES is not designed solely for DPLMTUD. RES happens only when DPMPLUD (or some other middle layer/OS) sends it and the default is to NOT send it; the UDP layer NEVER sends RES of its own accord.

**Comment by Mike-Heard** [comment]
I have to agree with Joe on this point ... the UDP options spec should not mandate that DLPMTUD is the only allowed use of REQ/RES.

**Comment by gorryfair** [comment]
We are close to agreeing, but the thread is confusing. I was wanting an *example*, as in the DPLPMTUD spec for UDP Options that adds that The new words look good, but we ought to have gone further when we note DPLPMTUD …. initiate UDP responses in the absence of user transmission

I think we ought to go further and add words... this is what the spec says for the way DPLPMTUD will use this:

  "Use of DPLPMTUD MUST be explicitly enabled by the application, for
   instance once an application has established connectivity and is
   ready to exchange data with the remote Upper Layer protocol.
   Similarly, a receiver SHOULD NOT respond to a REQ Option until
   DPLPMTUD has been enabled."

**Comment by gorryfair** [comment]
I should have been clearer, the sentence I wished to suggest was: "For example, an application has to explicitly enable the generation of a RES response by DPLPMTUD when using UDP Options [ID.REF]."

**Comment by jtouch** [comment]
Text added as Gorry suggested above in -25. Please let me know if that closes this issue or if additional text is needed.
