### ISSUE TITLE
Could we avoid being judgmental about design of middleboxes?

### ISSUE THREAD

**Issue by gorryfair** [tsvwg/draft-ietf-tsvwg-udp-options#17]
I personally do dislike the words chosen here : “The design enables traversal of misbehaving middleboxes that incorrectly compute the UDP checksum over the entire IP payload”. To me, it is great for a research paper, but awkward for a standard because it sounds like a judgment on the way others do things, well maybe it is. Could we we can find more positive text and say what it does?

Such as “This design enables traversal of a middlebox that has been designed to compute the UDP checksum over the entire IP payload”.
This also applies to later use of "misbehaving middlebox"

**Comment by jtouch** [comment]
This is a standards document. Middleboxes that compute UDP checksums based on IP lengths are objectively misbehaving and incorrect in their computation. This isn't a research assessment. If it belongs anywhere, it belongs in a spec affected by that decision, IMO. We previously called them misbehaving and errant. They're wrong in what they do. Is there a preferred term for such?

**Comment by gorryfair** [comment]
I'd persoanlly prefer to just say middleboxes that do not comply with RFCxxxx. That's more polite and helpful than  saying "errant" or "misbehaving".

**Comment by Mike-Heard** [comment]
I thought the word "errant" (which was used before) was more elegant than "misbehaving"  😃

**Comment by jtouch** [comment]
Errant is fine to me; I can unify around that term if useful.

**Comment by gorryfair** [comment]
I agree: Errant with respect to the spec seems a statement of fact!

**Comment by jtouch** [comment]
Changed all occurrences in -24 to "errant"

**Comment by gorryfair** [comment]
This was agreed at the Interim.
