### ISSUE TITLE
Add design principles per IETF 117 slide deck

### ISSUE THREAD

**Issue by jtouch** [tsvwg/draft-ietf-tsvwg-udp-options#18]
Add the following to the introductory material as design principles:
https://datatracker.ietf.org/meeting/117/materials/slides-117-tsvwg-sessb-42-udp-options-issues-from-github-00

A.) UDP is stateless; UDP options do not change that
- Any state must be managed either by the application or a layer/library on behalf of the application - Reassembly of fragments is a limited exception

B.) UDP is unidirectional; UDP options do not change that
- Responses to options are initiated by the application or a layer/library on behalf of the application - Any mechanism that requires bidirectionally needs to be defined in a separate document

C.) UDP options have no length limit separate from that of the UDP packet itself
- Past experience confirms that static limits will always be exceeded
- Each implementation can limit how long/many options there are, but the spec should not

D.) UDP options should not replace or replicate other protocols
- This includes NTP, ICMP (notably echo), etc.

E.) UDP options are a framework
- Options may be defined even when the details are not sufficient to implement - Uses of such options may then be described in other documents

**Comment by jtouch** [comment]
Done in -24.

**Comment by Mike-Heard** [comment]
The new text is an excellent addition to the specification; I do, however, see a need for some polishing:

- There are six principles listed, but the lead-in text says that there ae five.
- The explanatory paragraph after principle No. 6 refers to "checksums" without qualification. This could be interpreted to include the UDP checksum itself, and that is not the intent (packets with bad UDP checksums are discarded, as they always have been). Additionally, there is lingering controversy as to whether this is the desired behavior for certain options (see "#21"); if the resolution of that controversy is to remove or redesign those options, then the explanatory text will needs to change accordingly.

**Comment by jtouch** [comment]
Fixed in -25

**Comment by jtouch** [comment]
Fixed in -25
