### ISSUE TITLE
Typo in draft-ietf-tsvwg-udp-options-23 Section 9.1

### ISSUE THREAD

**Issue by Mike-Heard** [tsvwg/draft-ietf-tsvwg-udp-options#19]
OLD:
   >> Bytes after EOL in the surplus area MAY be checked as being zero
   on receipt, but MUST be otherwise processed (except for OCS
   calculation, which zeros would not affect) and are not passed to the
   user (e.g., as part of the surplus area).

NEW:
   >> Bytes after EOL in the surplus area MAY be checked as being zero
   on receipt, but MUST NOT be otherwise processed (except for OCS
   calculation, which zeros would not affect) or passed to the
   user (e.g., as part of the surplus area).

(missing NOT; include passing to the used in the scope of MUST NOT)

**Comment by jtouch** [comment]
fixed in -24 the second part with "and MUST NOT be passed" to be more clear.

**Comment by gorryfair** [comment]
Resolved in -24
