### ISSUE TITLE
Suggestion for reduced RDOS text

### ISSUE THREAD

**Issue by gorryfair** [tsvwg/draft-ietf-tsvwg-udp-options#2]
I think if the following text is
removed from Section 9.4, the rest of the section will make sense. 
--cut here--
   If RDOS is larger than Frag. Start of the first fragment (offset=8),
   then all the per-packet options occur before the user data as it is
   reassembled. If RDOS points to the end of the original IP packet,
   then there are no per-packet options. If RDOS is smaller than Frag.
   Start of the first fragment, then it indicates the end of the per-
   fragment options (of the first fragment) and the start of per-packet
   options (of the reassembled user data). The RDOS field enables the
   FRAG option to precede other options in every fragment and to enable
   all packet options to precede user data, enabling easier support for
   reassembly offload via DMA and to support limited router option
   processing hardware.
--end--

**Comment by Mike-Heard** [comment]
The above was one of two paragraphs that I propose to eliminate. This was the second:

--cut here--
      Note: per packet options can occur either at the end of the
      original user data or be placed after the FRAG option of the
      first segment, with the Reassembled Datagram Option Start (RDOS)
      in the terminal FRAG option set accordingly. This includes its
      use in atomic fragments, where the terminal option is the initial
      and only fragment.
--end--

**Comment by Mike-Heard** [comment]
Like Issue #1, this is also related to

https://mailarchive.ietf.org/arch/msg/tsvwg/D99trU_nsq4rRGT24gNeeDnkfoE/

**Comment by Mike-Heard** [comment]
Specific text to fix the issues with Section 9.4 was suggested in:

https://mailarchive.ietf.org/arch/msg/tsvwg/0RptobbqczCVoOy-B8L_CJaj25w/

**Comment by jtouch** [comment]
Text incorporated; these paragraphs deleted (I think) in -23. Please let me know if further consideration is needed.

**Comment by gorryfair** [comment]
Discussed at Interim and closed.

**Comment by jtouch** [comment]
The two paragraphs are now deleted in -33.
