### ISSUE TITLE
The API extensions for UDP Options must allow UDP fragmentation to be on or off for any send request

### ISSUE THREAD

**Issue by Mike-Heard** [tsvwg/draft-ietf-tsvwg-udp-options#24]
Appearing at the end of Section 15 of -26 (and persisting in the current version, -28) I see:

   APIs are not intended to provide user control over option order,
   especially on a per-packet basis, as this could create a security
   issue, although there are means to address this at receivers (see
   Section 24). Similarly, APIs are not intended to provide
   user/application control over UDP fragmentation on a per-packet
   basis.

That last sentence is problematic. The upper layer MUST be able to
specify, for any send request, whether fragmentation is allowed or not.
DPLPMTUD, when implemented as a library on top of UDP Options, won't
work if UDP fragmentation cannot be suppressed on probe packets. I
thought that we had a firm consensus on that point.

If the intent is that the application is not supposed to have
fine-grained control over what goes into fragments, I'm all in, but
the text needs to be reworded to say that.

Additionally, I think that the first sentence would be improved if
it were rewritten as follows:

   APIs are not intended to provide user control over option order,
   especially on a per-packet basis, as this could create a covert
   channel (see Section 24 for further discussion).

Mailing list reference: https://mailarchive.ietf.org/arch/msg/tsvwg/XCcF_rMNv0nLKSj9Hnl6NDm-wtw/

**Comment by jtouch** [comment]
Agreed; the original intent was that the API doesn't control HOW fragmentation happens. I still think that's worth including, though yes, it should be able to be enabled/disabled on a per-packet basis.

**Comment by jtouch** [comment]
Fixed in -29

**Comment by Mike-Heard** [comment]
I'm closing the issue with the following suggestion for a typo fix and a minor editorial change:

Current -29 text: 
>  APIs are not intended to provide user control over option order,
>  especially on a per-packet basis, as this could create a cover
>  channel (see [Section 24]). Similarly, APIs are not intended to
>  provide user/application control over UDP fragment boundaries on a
>   per-packet basis, although they are expected to allow control over
>   which options are enabled (or disabled) on a per-packet basis. Such
>   control over when fragmentation is used is critical to DPLPMTUD.

Proposed update:
>  APIs are not intended to provide user control over option order,
>  especially on a per-packet basis, as this could create a **covert**
>  channel (see [Section 24]). Similarly, APIs are not intended to
>  provide user/application control over UDP fragment boundaries on a
>   per-packet basis, although they are expected to allow control over
>   which options, **including fragmentation**, are enabled (or disabled) on
>   a per-packet basis. Such control over when fragmentation is used is
>   critical to DPLPMTUD.

I.e.:
s/cover channel/covert channel/
s/which options are/which options, including fragmentation, are/

**Comment by jtouch** [comment]
Fixed in -31.

Joe

—
Dr. Joe Touch, temporal epistemologist
www.strayalpha.com

**Comment by jtouch** [comment]
Fixed in -32.
