### ISSUE TITLE
WGLC issue: Check draft name citation for [To24], rev -31

### ISSUE THREAD

**Issue by gorryfair** [tsvwg/draft-ietf-tsvwg-udp-options#27]
/draft-touch-tsvwg-auth-option/draft-touch-tsvwg-udp-auth-opt/

**Comment by Mike-Heard** [comment]
I think you can expect to see this fixed in -32 when it appears. See [this comment](https://github.com/tsvwg/draft-ietf-tsvwg-udp-options/issues/5#issuecomment-2001989446) and [this response](https://github.com/tsvwg/draft-ietf-tsvwg-udp-options/issues/5#issuecomment-2002085101) in Issue #5

**Comment by jtouch** [comment]
Fixed in -32.
