### ISSUE TITLE
Med: WGLC Comments on Frag

### ISSUE THREAD

**Issue by gorryfair** [tsvwg/draft-ietf-tsvwg-udp-options#30]
* Glad to see that FRAG use is now "limited" and even with a limit lower than what was suggested in [1]
* However, this text seems to not condition the "able to generate..." frag to the limit set in Section 11.4:

   >> An endpoint supporting UDP options MUST support those marked with
   a "*" above: EOL, NOP, APC, FRAG, MDS, MRDS, REQ, and RES. This
   includes both recognizing and being able to generate these options
   if configured to do so. These are called "must-support" options.

Adding a note would be helpful.

* I suggest to cite DNSSEC given that this was the main driver for the FRAG option. It is better to highlight that.

[1] https://mailarchive.ietf.org/arch/msg/tsvwg/wholRDLrBiSt0URtRmZ7kY8ixSg/

(Added by GF during WGLC)

**Comment by Mike-Heard** [comment]
> - I suggest to cite DNSSEC given that this was the main driver for the FRAG option. It is better to highlight that.

Zahed Sarker has also stated "I agree it would useful to record this usecase." See:

https://mailarchive.ietf.org/arch/msg/tsvwg/xC4M6R0nAmSLgjC-2yGgffk37YI/

One of my action items is to write a short draft. More to come.

**Comment by Mike-Heard** [comment]
> > * I suggest to cite DNSSEC given that this was the main driver for the FRAG option. It is better to highlight that.
> 
> Zahed Sarker has also stated "I agree it would useful to record this usecase." See:
> 
> https://mailarchive.ietf.org/arch/msg/tsvwg/xC4M6R0nAmSLgjC-2yGgffk37YI/
> 
> and Issue #42. One of my action items is to write a short draft. More to come.

That draft has now been posted; see https://datatracker.ietf.org/doc/html/draft-heard-dnsop-udp-opt-large-dns-responses.  Comments have been requested from DNSOP.

**Comment by Mike-Heard** [comment]
> > > * I suggest to cite DNSSEC given that this was the main driver for the FRAG option. It is better to highlight that.
> > 
> > Zahed Sarker has also stated "I agree it would useful to record this usecase." [ ... ] One of my action items is to write a short draft. More to come.
> 
> That draft has now been posted; see https://datatracker.ietf.org/doc/html/draft-heard-dnsop-udp-opt-large-dns-responses. Comments have been requested from DNSOP.

DNSOP interest has not been overwhelming, to say the least. To date there has been only one comment, and it was not favorable. See https://mailarchive.ietf.org/arch/msg/dnsop/EhUq8tZF8Qm-iZk4eUAnjsCGXUg/ and subsequent messages in the thread. Additionally, as noted in the Discussion section of the draft, it is not a slam-dunk that UDP fragmentation would save significant resources compared to fallback to TCP. Based on that, it's not clear that it is appropriate to highlight this use case. The only other UDP request/response protocol with potentially large responses that comes to mind is SNMP, and I don't think that is much used anymore.

**Comment by Mike-Heard** [comment]
Recent discussion on the tsvwg and v6ops lists suggests that there is still interest in this use case, just not from DNSOP (see the thread starting with https://mailarchive.ietf.org/arch/msg/tsvwg/YG7jeLoD8nLrgzpdhZxbegR8sfY/). One point of view is that whether the DNS community thinks this isn’t needed or not is less the issue than that it COULD be useful to them.

**Comment by jtouch** [comment]
Agree with adding a note as Med originally suggested to clarify the frag issue. The rest of this is covered in #42

**Comment by Mike-Heard** [comment]
> Requested text added in -33 Section 5.

Specifically, the text shown below in **bold** was added to the last paragraph of Section 5:

> UDP was originally intended to assume such capabilities could be provided by the user or by a layer above UDP. However, enough protocols have evolved to use UDP directly, so such an intermediate layer would be difficult to deploy for legacy applications. UDP options leverage the opportunity presented by the surplus area to enable these extensions within the UDP transport layer itself. **Among the use cases where this approach could be of benefit are request-response protocols such as DNS over UDP [He24]**.

Note: [He24] is an informative reference to [draft-heard-dnsop-udp-opt-large-dns-response](https://datatracker.ietf.org/doc/html/draft-heard-dnsop-udp-opt-large-dns-responses)s

Kindly let me know whether the proposed resolution is satisfactory or still needs work.

**Comment by Mike-Heard** [comment]
Med: please see Issue #52 and [https://mailarchive.ietf.org/arch/msg/tsvwg/YHqTpgGysV2nnxYltQQ9Gi5Nsrw/](https://mailarchive.ietf.org/arch/msg/tsvwg/YHqTpgGysV2nnxYltQQ9Gi5Nsrw/) for a proposal for 3 frags / 3600 bytes and let us know if this changes your position on this issue. Also please see the previous github comment on this issue (#30) and let us know if that addresses your use case request.

**Comment by boucadair** [comment]
> Requested text added in -33 Section 5.

Looks good to me. Thanks.
