### ISSUE TITLE
Med: WGLC Minor NiTs

### ISSUE THREAD

**Issue by gorryfair** [tsvwg/draft-ietf-tsvwg-udp-options#33]
* Some minor nits:

(1) I don't remember that I have seen "Diff Svcs" in a RFC
      +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
      |Version|  IHL  |   Diff Svcs   |          Total Length         |
      +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+

(2) Not all options have a "length" 

   The remainder of the surplus area consists of options defined using
   a TLV (type, length, and optional value)

(Added by GF during WGLC)

**Comment by gorryfair** [comment]
I expect DS field or DSCP ought to be used in place of "Diff Svcs"

**Comment by jtouch** [comment]
Both items fixed in -33.
