### ISSUE TITLE
Tom H: WGLC comments on Section  7: OCS

### ISSUE THREAD

**Issue by gorryfair** [tsvwg/draft-ietf-tsvwg-udp-options#37]
Please change "Next HDR" to "Next Header" to be consistent with RFC8200

"In effect, this document redefines the UDP "Length" field as a
"trailer options offset"."

This text seems unnecessary. I would simply say that the surplus area
offset can is derived from the UDP Length

"They commence with a 2-byte Option Checksum (OCS) field aligned to
the first  byte boundary (relative to the start of the IP datagram) of
that area, using zeroes for alignment."

This description should be more specific. i.e. if the offset from the
first byte of the UDP header is even then OCS begins at the surplus
area, if the offset is off then there is a zero byte followed by the
OCS

"OCS is not intended to prevent future non-standard uses of the
surplus area, nor does it enable shared use with mechanisms that do
not comply with UDP options."

(Added by GF during WGLC)

**Comment by Mike-Heard** [comment]
I am OK with changing "Next HDR" to "Next Header" to be consistent with RFC8200. I see no need to adopt the rest of the proposed changes.

**Comment by Mike-Heard** [comment]
This change is now in the editor's copy of -33.
