### ISSUE TITLE
Section 9.9: Is AUTH sufficiently mature for LC as PS?

### ISSUE THREAD

**Issue by gorryfair** [tsvwg/draft-ietf-tsvwg-udp-options#5]
Raised by Magnus Westerlund here: https://mailarchive.ietf.org/arch/msg/tsvwg/mAiwXGMLx87AapktheAgfZQJJ4s/
Query in WGLC about whether this is sufficiently mature for LC as PS, and suggestion that this is placed in a separate draft (resolution needed).
Security Area review request may provide more inputs.

**Comment by Mike-Heard** [comment]
> Raised by Magnus Westerlund here: https://mailarchive.ietf.org/arch/msg/tsvwg/mAiwXGMLx87AapktheAgfZQJJ4s/ 

See also https://mailarchive.ietf.org/arch/msg/tsvwg/fVhpq4z427WnytB_anAqRcprUik/

**Comment by jtouch** [comment]
As of -29, UTH has been extracted as a separate document intended for experimental track, draft-touch-tsvwg-auth-option.

**Comment by gorryfair** [comment]
Closing this issue to allow discussion in the separate EXP draft.

**Comment by Mike-Heard** [comment]
Typo for -32: for [To24], /draft-touch-udp-auth-option./draft-touch-tsvwg-udp-auth-opt/

**Comment by jtouch** [comment]
Fixed in -32, when posted.
