### ISSUE TITLE
NiT (Erik):  Section 6

### ISSUE THREAD

**Issue by gorryfair** [tsvwg/draft-ietf-tsvwg-udp-options#50]
> 6. The UDP option mechanism and UDP options themselves should
>       default to the same behavior experienced by a legacy receiver.
>
>       By default, even when option checksums (OCS, APC),
>       authentication, or **encryption** fail, every received packet is

A small nit: I would expect the receiver to attempt decryption, not encryption.

**Comment by Mike-Heard** [comment]
Text in editor's copy of -33 changed as follows:

OLD:
>By default, even when option checksums (OCS, APC), authentication, or encryption fail, every received packet is passed (possibly with an empty data payload) to the user application.

NEW:
> By default, even when option checksums (OCS, APC), authentication, or decryption fail, every received packet (with the exception of UDP fragments) is passed (possibly with an empty data payload) to the user application.
