### ISSUE TITLE
CMH:  Clarify the exact meaning of MRDS size

### ISSUE THREAD

**Issue by Mike-Heard** [tsvwg/draft-ietf-tsvwg-udp-options#54]
In Section 11.6 please replace

>   The Maximum Reassembled Datagram Size (MRDS, Kind=5) option is a 16-
>   bit indicator of the largest reassembled UDP datagram that can be
>   received.

with

>   The Maximum Reassembled Datagram Size (MRDS, Kind=5) option is a 16-
>   bit indicator of the largest reassembled UDP datagram that can be
>   received, including the UDP header and any UDP options.

This is intended to clarify that the MRDS size is intended to be that of the original UDP datagram shown in Figure 12, including all UDP options.

**Comment by gorryfair** [comment]
I agree, clarification is needed.

**Comment by jtouch** [comment]
MRDS is defined as similar to IP’s EMTU_R, which is a reference to the buffer area for reassembly. For IP, that does include the IP options (which are copied per fragment). For us, it would NOT include the per-fragment UDP options but would include the per-datagram UDP options.  I.e., it’s the UDP datagram with options that would have been sent had fragmentation not been needed. 

Please confirm whether you think that makes the most sense as being most useful.

**Comment by Mike-Heard** [comment]
> MRDS is defined as similar to IP’s EMTU_R, which is a reference to the buffer area for reassembly. For IP, that does include the IP options (which are copied per fragment). For us, it would NOT include the per-fragment UDP options but would include the per-datagram UDP options. I.e., it’s the UDP datagram with options that would have been sent had fragmentation not been needed.
> 
> Please confirm whether you think that makes the most sense as being most useful.

This sounds right. Text to that effect will be added to -33.

**Comment by Mike-Heard** [comment]
> For us, it would NOT include the per-fragment UDP options but would include the per-datagram UDP options. I.e., it’s the UDP datagram with options that would have been sent had fragmentation not been needed.

Agreed, and the text in the editor's copy of -33 now has the bolded text added:

> The Maximum Reassembled Datagram Size (MRDS, Kind=5) option is a 16-bit indicator of the largest reassembled UDP datagram that can be received, **including the UDP header and any per-datagram UDP options**. 

Apologies for not posting this earlier.
