### ISSUE TITLE
Erik: correct or remove erroneous note in Step 3 of the fragmentation procedure (Section 11.4)

### ISSUE THREAD

**Issue by Mike-Heard** [tsvwg/draft-ietf-tsvwg-udp-options#57]
In https://mailarchive.ietf.org/arch/msg/tsvwg/SjPKGD-yxp2-Cf7TFGyKCCA7e8I/,
Erik Auerswald wrote:

I do not understand the "Note" in enumeration item 3 of the
fragmentation procedure in section 11.4, "Fragmentation (FRAG)"
on page 25:

     "Note: per packet options can occur either at the end of the
      original user data or be placed after the FRAG option of the
      first fragment, with the Reassembled Datagram Option Start (RDOS)
      in the terminal FRAG option set accordingly. This includes its
      use in atomic fragments, where the terminal option is the initial
      and only fragment."

How exactly would RDOS be set to indicate that the per-packet (a.k.a
per-datagram) options are located outside the reassembled datagram
after the FRAG option of the first fragment[, but before the fragment
data], in the case non-atomic fragments?  RDOS is a positive offset
from the start of the reassembled datagram (a.k.a. packet).

It seems to me as if this note should be deleted.  Alternatively,
it could be simplified to pertain only to atomic fragments, e.g.:

      In atomic fragments, where the the terminal option is the initial
      and only fragment, both per-fragment and per-datagram options
      affect the same UDP payload.

**Comment by Mike-Heard** [comment]
The correct solution is to delete the whole paragraph, since there
are now explicit instructions in the definition of each option on
how to collect per-fragment options and pass them to the
user/application. Note that the definition of APC is such that it
is not useful as a per-fragment option, even in an atomic fragment;
it must be sent as a per-datagram option in order to be useful.

**Comment by Mike-Heard** [comment]
In https://mailarchive.ietf.org/arch/msg/tsvwg/DtWdOh9sGcoPMJAC8Mb-Pp_q9iM/,
Erik Auerswald wrote:

You are right, my suggested replacement is wrong.  I concur that the
paragraph should be deleted.

Best regards,
Erik

**Comment by jtouch** [comment]
Deleted in -33.
