### ISSUE TITLE
* Section 10.1: UENC downref?

### ISSUE THREAD

**Issue by gorryfair** [tsvwg/draft-ietf-tsvwg-udp-options#6]
Encryption: WGLC noted this would be a down-ref and should not be a part of a PS (resolution needed - GF will propose on list).

**Comment by gorryfair** [comment]
MW's comments are here: https://mailarchive.ietf.org/arch/msg/tsvwg/mAiwXGMLx87AapktheAgfZQJJ4s/

**Comment by Mike-Heard** [comment]
See also thread beginning at https://mailarchive.ietf.org/arch/msg/tsvwg/QeVu-_sukrW7zTWCdfuls6__F1Y/

**Comment by jtouch** [comment]
As of -29, AUTH and UENC (as well as now UCMP for compression) kept as a placeholders and used as examples for discussion, but not defined (code points are marked reserved with intended future use, but not yet assigned)..

**Comment by gorryfair** [comment]
Resolved in latest version
