### ISSUE TITLE
add pointer to UDP-ipfix

### ISSUE THREAD

**Issue by jtouch** [tsvwg/draft-ietf-tsvwg-udp-options#60]
From Med mohamed.boucadair@orange.com

BTW, I wonder whether udp-options I-D can include a sentence to inform the reader that some manageability features are provided in draft-ietf-opsawg-tsvwg-udp-ipfix. Thanks.

**Comment by jtouch** [comment]
Agreed - this should be added.

**Comment by Mike-Heard** [comment]
Added to editor's tracking sheet. Text will be forthcoming in -33.

**Comment by Mike-Heard** [comment]
The following section has been added to the editor's copy of -33:

> 24. Management Considerations
> 
> IP Flow Information Export Information Elements for UDP options have been defined in [Bo24].

Also, the following reference has been added:

> [Bo24] Boucadair, M., and T. Reddy.K, “Export of UDP Options Information in IP Flow Information Export (IPFIX)”, draft-ietf-opsawg-tsvwg-udp-ipfix, Jul. 2024.
