### ISSUE TITLE
* Section 16: rename section?

### ISSUE THREAD

**Issue by gorryfair** [tsvwg/draft-ietf-tsvwg-udp-options#7]
There was one question about where NAT traversal is discussed - One step might be to rename this section: " Interactions with Legacy Hosts and Legacy Devices on the Path"?

**Comment by Mike-Heard** [comment]
Note that Section 6 (OCS) says:

The design enables traversal of errant middleboxes that incorrectly
 compute the UDP checksum over the entire IP payload [Fa18], rather
 than only the UDP header and UDP payload (as indicated by the UDP
 header length).

What other middlebox traversal issues pertaining specifically to options need to be discussed? If there are none, I would contend that what is present is sufficient and that no change is needed. It would be reasonable to add a reference to https://tma.ifip.org/2020/wp-content/uploads/sites/9/2020/06/tma2020-camera-paper70.pdf, however.

**Comment by gorryfair** [comment]
The two things I know are: size of final IP packet (MTU) and checksum computation.

**Comment by Mike-Heard** [comment]
> The two things I know are: size of final IP packet (MTU) and checksum computation.

It would be helpful (for me at least) to under stand what the spec needs to say about MTU that is relevant specifically to middlebox traversal, given that to many of us the normal action of a router discarding a packet that is too large for an outgoing link is not normally discussed under the head of "middlebox issues" or "NAT traversal issues."

As for checksum computation, do you feel that the existing text in the OCS section is inadequate?

**Comment by gorryfair** [comment]
I also do not think PMTU is a specific topic that needs to be discussed in a middle box section. If the datagram is too big it is dropped.GorryOn 20 Jul 2023, at 13:31, Mike-Heard ***@***.***> wrote:﻿

The two things I know are: size of final IP packet (MTU) and checksum computation.

It would be helpful (for me at least) to under stand what the spec needs to say about MTU that is relevant specifically to middlebox traversal, given that to many of us the normal action of a router discarding a packet that is too large for an outgoing link is not normally discussed under the head of "middlebox issues" or "NAT traversal issues."
As for checksum computation, do you feel that the existing text in the OCS section is inadequate?

**Comment by jtouch** [comment]
Not sure I understand what is being suggested yet. Added ref to the paper above to -23, but no other changes yet. Please suggest a way forward.

**Comment by gorryfair** [comment]
I suggest we close this with no further action.

**Comment by Mike-Heard** [comment]
> I suggest we close this with no further action.

I concur.

Gorry, you opened the issue, so maybe it would be good for you to close it.
